name: CtDEnvTest6
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - aiohttp-cors=0.7.0=pyhd3eb1b0_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anyio=3.7.1=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_0
  - arrow-cpp=11.0.0=h374c478_2
  - asttokens=2.4.1=pyhd8ed1ab_0
  - aws-c-common=0.6.8=h5eee18b_1
  - aws-c-event-stream=0.1.6=h6a678d5_6
  - aws-checksums=0.1.11=h5eee18b_2
  - aws-sdk-cpp=1.8.185=h721c034_1
  - backoff=2.2.1=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - boto3=1.34.6=pyhd8ed1ab_0
  - botocore=1.34.6=pyhd8ed1ab_0
  - brotli-python=1.0.9=py310h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2023.11.17=hbcca054_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2023.11.17=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorful=0.5.4=pyhd3eb1b0_0
  - comm=0.2.1=pyhd8ed1ab_0
  - croniter=1.4.1=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - dateutils=0.6.12=py_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deepdiff=5.8.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - fastapi=0.103.2=pyhd8ed1ab_0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.12.2=pyhca7485f_0
  - gflags=2.2.2=he6710b0_0
  - giflib=5.2.1=h5eee18b_3
  - glog=0.5.0=h2531618_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - grpc-cpp=1.48.2=he1ff14a_1
  - h11=0.14.0=pyhd8ed1ab_0
  - hdf5=1.12.1=h2b7332f_3
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.28.0=pyhd33586a_0
  - ipython=8.20.0=pyh707e725_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py310hff52083_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.101=0
  - libcurl=8.4.0=h251f7ec_1
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libunwind=1.5.0=h295c915_1
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lightning=2.1.3=pyhd8ed1ab_0
  - lightning-cloud=0.5.57=pyhd8ed1ab_0
  - lightning-utilities=0.10.0=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - msgpack-python=1.0.3=py310hd09550d_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.26.2=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.0.12=h7f8727e_0
  - orc=1.7.4=hb3bc3d3_1
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-spy=0.3.14=h52d8a92_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - python=3.10.13=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-dotenv=1.0.0=pyhd8ed1ab_1
  - python-editor=1.0.4=py_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.1.2=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-lightning=2.1.3=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - ray-core=2.6.3=py310h6a678d5_2
  - ray-dashboard=2.6.3=py310h06a4308_2
  - ray-default=2.6.3=py310h06a4308_2
  - ray-tune=2.6.3=py310h06a4308_2
  - re2=2022.04.01=h295c915_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h5eee18b_0
  - rich=13.7.0=pyhd8ed1ab_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s3transfer=0.10.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - smart_open=5.2.1=py310h06a4308_0
  - snappy=1.1.10=h6a678d5_1
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboardx=2.2=pyhd3eb1b0_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tk=8.6.12=h1ccaba5_0
  - torchmetrics=1.2.1=pyhd8ed1ab_0
  - torchtriton=2.1.0=py310
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.14.0=pyhd8ed1ab_0
  - types-python-dateutil=2.8.19.14=pyhd8ed1ab_0
  - typing_extensions=4.7.1=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - utf8proc=2.6.1=h27cfd23_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - aiohttp==3.9.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - blessed==1.20.0
      - bottleneck==1.3.5
      - brotli==1.0.9
      - cffi==1.16.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - contourpy==1.2.0
      - cryptography==41.0.7
      - cycler==0.12.1
      - debugpy==1.6.7
      - distlib==0.3.6
      - docker-pycreds==0.4.0
      - farama-notifications==0.0.4
      - filelock==3.13.1
      - fonttools==4.47.0
      - frozenlist==1.4.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - gmpy2==2.1.2
      - google-api-core==2.10.1
      - google-auth==2.22.0
      - googleapis-common-protos==1.56.4
      - gpustat==1.1.1
      - grpcio==1.59.3
      - gymnasium==0.29.1
      - h5py==3.9.0
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - inquirer==3.1.4
      - ipympl==0.9.3
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - jinja2==3.1.2
      - jsonschema==4.19.2
      - jsonschema-specifications==2023.7.1
      - jupyter-core==5.7.1
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - markupsafe==2.1.1
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - msgpack==1.0.3
      - multidict==6.0.4
      - networkx==3.1
      - numexpr==2.8.7
      - numpy==1.26.2
      - nvidia-ml-py==12.535.133
      - nvitop==1.3.2
      - omegaconf==2.3.0
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - opencv-python==4.9.0.80
      - packaging==23.1
      - pillow==9.5.0
      - pip==23.3.1
      - platformdirs==2.5.2
      - protobuf==3.20.3
      - psutil==5.9.0
      - pyarrow==11.0.0
      - pydantic==1.10.12
      - pyopenssl==23.2.0
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - ray==2.6.3
      - referencing==0.30.2
      - requests==2.31.0
      - rpds-py==0.10.6
      - scikit-learn
      - scipy
      - sentry-sdk==1.39.1
      - setproctitle==1.2.2
      - setuptools==68.2.2
      - smart-open==5.2.1
      - smmap==5.0.1
      - sympy==1.12
      - termcolor==2.4.0
      - torch==2.1.2
      - torchaudio==2.1.2
      - torchvision==0.16.2
      - tornado==6.1
      - triton==2.1.0
      - typing-extensions==4.7.1
      - urllib3==1.26.18
      - uvicorn==0.24.0.post1
      - virtualenv==20.17.1
      - wandb==0.16.1
      - websockets==10.4
      - wheel==0.41.2
      - widgetsnbextension==4.0.9
      - yarl==1.9.3
prefix: /home/csverst/miniconda3/envs/CtDEnvTest6
