_target_: ctd.data_modeling.datamodules.SAE.task_trained_data.TaskTrainedRNNDataModule
prefix: tt_MultiTask
n_neurons: 50
embed_dict:
  rect_func: exp
  fr_scaling: 2.0
noise_dict:
  obs_noise: pseudoPoisson
  dispersion: 1.0
seed: 0
batch_size: 250
num_workers: 4
provide_inputs: True
