_target_: ctd.data_modeling.models.SAE.dyn_models_GRU.GRULatentSAE
dataset: RandomTargetDelay

encoder_size: 100
encoder_window: -1

heldin_size: 50
heldout_size: 60
latent_size: 64
input_size: 17

weight_decay: 1e-6
lr: 5e-3

dropout: 0.2
