_target_: ctd.task_modeling.task_env.multi_task_env.MultiTaskWrapper
dataset_name: MultiTask
task_list:
  - DelayPro
  - DelayAnti
  - MemoryPro
  - MemoryAnti
  - ReactPro
  - ReactAnti
  - IntMod1
  - IntMod2
  - ContextIntMod1
  - ContextIntMod2
  - ContextIntMultimodal
  - Match2Sample
  - NonMatch2Sample
  - MatchCatPro
  - MatchCatAnti

n_timesteps: 640
noise: 0.3
num_targets: 32
bin_size: 20
grouped_sampler: True
