_target_: pytorch_lightning.Trainer
log_every_n_steps: 20
max_epochs: 1000
gradient_clip_val: 0.01
# Prevent console output from individual models
enable_progress_bar: False
# weights_summary: null
#auto_scale_batch_size: True
